# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
#
# Travis CI configuration
# https://docs.travis-ci.com/
---
# Run tests against pull requests and main branches only
if: |
  type = pull_request OR \
  branch IN (master, develop)

dist: xenial
os: linux
language: generic

before_install:
  # Existing pyenv installation on Linux conflicts with ours
  - >
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      rm -rf /opt/pyenv
    fi

install:
  # Install Ansible with pip on Ubuntu
  - >
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      if [[ -z "$ANSIBLE_VERSION" ]]; then
        ${PIP_BIN} install --user ansible
      else
        ${PIP_BIN} install --user ansible${ANSIBLE_VERSION}
      fi
    fi

  # Check Ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\n' > ansible.cfg

before_script:
  # https://github.com/travis-ci/travis-ci/issues/6307
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      rvm get head || true
    fi

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # yamllint disable rule:line-length

  # Test role run
  - >
    if [[ "$FROM_PACKAGE_MANAGER" == "yes" ]]; then
      ansible-playbook tests/test.yml -i tests/inventory --connection=local \
        -e "{'pyenv_install_from_package_manager':true}" \
        || travis_terminate 1
    else
      ansible-playbook tests/test.yml -i tests/inventory --connection=local \
        -e "{'pyenv_install_from_package_manager':false}" \
        || travis_terminate 1
    fi

  # Debug idempotence test
  - >
    if [[ "$FROM_PACKAGE_MANAGER" == "yes" ]]; then
      ansible-playbook tests/test.yml -i tests/inventory --connection=local \
        -e "{'pyenv_install_from_package_manager':true}" \
        || travis_terminate 1
    else
      ansible-playbook tests/test.yml -i tests/inventory --connection=local \
        -e "{'pyenv_install_from_package_manager':false}" \
        || travis_terminate 1
    fi

  # Test idempotence
  - >
    if [[ "$FROM_PACKAGE_MANAGER" == "yes" ]]; then
      ansible-playbook tests/test.yml -i tests/inventory --connection=local \
      -e "{'pyenv_install_from_package_manager':true}" \
        | grep -q 'changed=0.*failed=0' \
        && (echo 'Idempotence test: pass' && exit 0) \
        || (echo 'Idempotence test: fail' && exit 1)
    else
      ansible-playbook tests/test.yml -i tests/inventory --connection=local \
      -e "{'pyenv_install_from_package_manager':failed}" \
        | grep -q 'changed=0.*failed=0' \
        && (echo 'Idempotence test: pass' && exit 0) \
        || (echo 'Idempotence test: fail' && exit 1)
    fi

  # yamllint enable rule:line-length

  # Test global python version is defined
  - . $HOME/.pyenv/.pyenvrc && pyenv version

stages:
  - validate
  - test

jobs:
  include:
    # Run validation stage in Linux with latest Ansible only
    - stage: validate
      name: Validate with pre-commit
      os: linux
      dist: focal
      language: shell
      addons:
        apt:
          packages:
            - python3-pip
            - python3-dev
          update: true
      cache:
        directories:
          - $HOME/.cache/pre-commit/
      before_cache:
        - rm -f $HOME/.cache/pre-commit/pre-commit.log
      install:
        - pip3 install --user -r requirements.dev.txt
      script:
        - pre-commit run -a

    # Run tests
    - stage: test
      name: "Ubuntu 16.04 (Xenial) with Ansible 2.7"
      os: linux
      dist: xenial
      env: ANSIBLE_VERSION='<2.8.0' PIP_BIN='pip'
      addons:
        apt:
          packages:
            - python-pip
            - python-dev
            - shellcheck
          update: true

    - stage: test
      name: "Ubuntu 18.04 (Bionic) with Ansible 2.8"
      os: linux
      dist: bionic
      env: ANSIBLE_VERSION='<2.9.0,!=2.8.6' PIP_BIN='pip'
      addons:
        apt:
          packages:
            - python-pip
            - python-dev
            - shellcheck
          update: true

    - stage: test
      name: "Ubuntu 20.04 (Focal Fossa) with Ansible 2.9"
      os: linux
      dist: focal
      env: ANSIBLE_VERSION='<2.10' PIP_BIN='pip3'
      addons:
        apt:
          packages:
            - python3-pip
            - python3-dev
          update: true

    - stage: test
      name: "macOS 10.13 (High Sierra) with Xcode 10.1 with Homebrew"
      os: osx
      osx_image: xcode10.1
      env: FROM_PACKAGE_MANAGER='yes'
      addons:
        homebrew:
          packages:
            - ansible
          update: true

    - stage: test
      name: "macOS 10.14 (Mojave) with Xcode 11.2 with Homebrew"
      os: osx
      osx_image: xcode11.2
      env: FROM_PACKAGE_MANAGER='yes'
      addons:
        homebrew:
          packages:
            - ansible
          update: true

    - stage: test
      name: "macOS 10.15.5 (Catalina) with Xcode 12.0 with Homebrew"
      os: osx
      osx_image: xcode12
      env: FROM_PACKAGE_MANAGER='yes'
      addons:
        homebrew:
          packages:
            - ansible
          update: true

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
